# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.5'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
#    - run: npm test
    - name: Upload Binaries
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Binaries
        path: dist/
  releases:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./artifacts
      - name: Zip Binaries
        run: |
          zip -jr windows.zip ./artifacts/Binaries/server-win.exe
          zip -jr mac.zip ./artifacts/Binaries/server-macos

      - name: Upload to Releases
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: |
            ./windows.zip
            ./mac.zip
        
